'use client';

import { useState } from 'react';
import ReactMarkdown from 'react-markdown';
import DownloadModal from './DownloadModal';

interface Props {
  markdown: string;
  sessionId: string;
}

export default function ReportView({ markdown, sessionId }: Props) {
  const [showModal, setShowModal] = useState(false);

  return (
    <>
      {/* Print header — only visible when printing */}
      <div className="print-header border-b border-slate-200 pb-4 mb-6">
        <div className="flex items-center justify-between">
          <div>
            <h1 className="text-2xl font-bold text-brand-900">CLAIR</h1>
            <p className="text-sm text-slate-500">Credit Limit AI Review</p>
          </div>
          <div className="text-right text-xs text-slate-400">
            <p>Generated: {new Date().toLocaleDateString('en-GB', { day: '2-digit', month: 'short', year: 'numeric' })}</p>
            <p>Advisory only — not a substitute for formal credit insurance</p>
          </div>
        </div>
      </div>

      {/* Screen controls */}
      <div className="no-print flex items-center justify-between mb-6">
        <div>
          <h1 className="text-2xl font-bold text-brand-900">Credit Assessment Report</h1>
          <p className="text-sm text-slate-500 mt-0.5">
            Generated {new Date().toLocaleDateString('en-GB', { day: '2-digit', month: 'short', year: 'numeric' })}
          </p>
        </div>
        <button
          onClick={() => setShowModal(true)}
          className="flex items-center gap-2 px-5 py-2.5 bg-brand-600 hover:bg-brand-700 text-white text-sm font-semibold rounded-lg transition"
        >
          <svg className="h-4 w-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
            <path d="M21 15v4a2 2 0 01-2 2H5a2 2 0 01-2-2v-4" />
            <polyline points="7 10 12 15 17 10" />
            <line x1="12" y1="15" x2="12" y2="3" />
          </svg>
          Download Report
        </button>
      </div>

      {/* Report content */}
      <div className="print-area report-body bg-white rounded-xl border border-slate-200 p-8 shadow-sm">
        <ReactMarkdown
          components={{
            // Render risk emoji badges with colour styling
            p({ children }) {
              const text = String(children);
              // Highlight decision lines
              if (text.includes('APPROVED')) {
                return (
                  <p className="font-bold text-green-700 text-lg bg-green-50 border border-green-200 rounded-lg px-4 py-3">
                    {children}
                  </p>
                );
              }
              if (text.includes('DECLINED')) {
                return (
                  <p className="font-bold text-red-700 text-lg bg-red-50 border border-red-200 rounded-lg px-4 py-3">
                    {children}
                  </p>
                );
              }
              if (text.includes('REFERRED')) {
                return (
                  <p className="font-bold text-orange-700 text-lg bg-orange-50 border border-orange-200 rounded-lg px-4 py-3">
                    {children}
                  </p>
                );
              }
              return <p>{children}</p>;
            },
          }}
        >
          {markdown}
        </ReactMarkdown>
      </div>

      {/* Disclaimer */}
      <div className="mt-6 p-4 bg-slate-100 rounded-lg text-xs text-slate-500 no-print">
        <strong>Disclaimer:</strong> This report is generated by an AI system and is advisory only. It is not a
        substitute for formal credit insurance decisions and does not constitute financial advice. CLAIR is an
        independent tool and is not affiliated with any credit insurer.
      </div>

      {/* Print disclaimer */}
      <div className="print-header mt-8 pt-4 border-t border-slate-200 text-xs text-slate-400">
        This report is advisory only. Not a substitute for formal credit insurance. CLAIR is not affiliated with any
        credit insurer. © {new Date().getFullYear()} CLAIR — Credit Limit AI Review.
      </div>

      {showModal && (
        <DownloadModal sessionId={sessionId} onClose={() => setShowModal(false)} />
      )}
    </>
  );
}
